### ISSUE TITLE
Evaluate `create_scale` necessity inside `generate.py`

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#20]
`create_scale` is not used anywhere in the code or notebooks. Also it is not clear the need to use CV2 to create an RGB image to represent grayscale data and plot it. 

The plotting is not appropriate to have inside the `generate.py` file

**Comment by cunhaJ** [comment]
A deprecation note should be added to ``create_scale`` function, as it was with other functions within  ``generate`` module. 

cv2 is as of version 1.1 being used to provide import-export functionalities, e.g. import-export .bmp files.

Since version 1.0 plotting has been progressively moved out of functions. Please create new issues when particular situations are identified.
